### ISSUE TITLE
短链接数过多

### ISSUE THREAD

**Issue by yaoxingshuai** [NETkiddy/cmq-go#1]
func (this *CMQHttp) request
这个函数里面每次都新建transport，频繁的使用短链接。客户端有大量的time_wait。能否复用transport改用长连接呢？

**Comment by NETkiddy** [comment]
make scene,
我晚点优化下

**Comment by NETkiddy** [comment]
e89d0ffa1d1bc7596dc86e979e9d8cece53437f9 add supported @yaoxingshuai 
两处改动：
1. 底层复用transport（采用了较大的MaxIdleConns和MaxIdleConnsPerHost以基本适合大部分场景）；
2. 暴露了Account.SetTransport()接口以支持自定义transport；
